[package]
name = "timeshift-tui-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
chrono = "0.4.42"
anyhow = "1.0.100"
derive_setters = "0.1.8"
indexmap = "2.12.1"
throbber-widgets-tui = "0.9.0"

